/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Classes.Livro;
import Classes.Autor;
import Classes.Editora;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bodao
 */
public class CadastroLivro extends javax.swing.JFrame {

    static ArrayList<Livro> listaLivro;
    
    String botao;
    int indexPesquisa = -1;
    
    public CadastroLivro() {        
        
        initComponents();
        
        //maximizar a tela
        //this.setExtendedState(MAXIMIZED_BOTH);
        
        listaLivro = new ArrayList();
        
        //habilitar e desabilitar botões
               
    }        
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCadastroLivro = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtTituloLivro = new javax.swing.JTextField();
        lblDataPublicacao = new javax.swing.JLabel();
        lblNumeroPaginas = new javax.swing.JLabel();
        txtNumeroPaginasLivro = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPrecoLivro = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        txtGeneroLivro = new javax.swing.JTextField();
        lblCopiasVendidas = new javax.swing.JLabel();
        txtCopiasVendidasLivro = new javax.swing.JTextField();
        lblAdicionarAutor = new javax.swing.JLabel();
        btnAdicionarAutor = new javax.swing.JButton();
        btnPesquisarLivro = new javax.swing.JButton();
        cmbLivroAutor = new javax.swing.JComboBox<>();
        txtDataPublicacaoLivro = new javax.swing.JFormattedTextField();
        btnLivroNovo = new javax.swing.JButton();
        btnLivroSalvar = new javax.swing.JButton();
        btnLivroCancelar = new javax.swing.JButton();
        btnLivroEditar = new javax.swing.JButton();
        btnLivroExcluir = new javax.swing.JButton();
        btnLivroPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        btnSairCadastroLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Filme");

        pnCadastroLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Filme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblTitulo.setText("Título:");

        txtTituloLivro.setToolTipText("Digite o título");
        txtTituloLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloLivroActionPerformed(evt);
            }
        });

        lblDataPublicacao.setText("Data Lançamento:");

        lblNumeroPaginas.setText("Duração");

        txtNumeroPaginasLivro.setToolTipText("Digite o número de páginas");

        lblPreco.setText("Preço:");

        txtPrecoLivro.setToolTipText("Digite o preço");

        lblGenero.setText("Gênero:");

        txtGeneroLivro.setToolTipText("Digite o gênero do livro");

        lblCopiasVendidas.setText("Cópias Vendidas:");

        txtCopiasVendidasLivro.setToolTipText("Digite quantidade vendidas");
        txtCopiasVendidasLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCopiasVendidasLivroActionPerformed(evt);
            }
        });

        lblAdicionarAutor.setText("Diretor:");

        btnAdicionarAutor.setText("Adicionar Diretor");
        btnAdicionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAutorActionPerformed(evt);
            }
        });

        btnPesquisarLivro.setText("OK");
        btnPesquisarLivro.setToolTipText("Confimar pesquisa");
        btnPesquisarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLivroActionPerformed(evt);
            }
        });

        cmbLivroAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Diretor" }));
        cmbLivroAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbLivroAutorMouseClicked(evt);
            }
        });
        cmbLivroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLivroAutorActionPerformed(evt);
            }
        });

        try {
            txtDataPublicacaoLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnCadastroLivroLayout = new javax.swing.GroupLayout(pnCadastroLivro);
        pnCadastroLivro.setLayout(pnCadastroLivroLayout);
        pnCadastroLivroLayout.setHorizontalGroup(
            pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLivroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDataPublicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumeroPaginas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCopiasVendidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblAdicionarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastroLivroLayout.createSequentialGroup()
                        .addComponent(cmbLivroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarAutor)
                        .addGap(17, 17, 17))
                    .addGroup(pnCadastroLivroLayout.createSequentialGroup()
                        .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCadastroLivroLayout.createSequentialGroup()
                                .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisarLivro))
                            .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCopiasVendidasLivro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(txtGeneroLivro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrecoLivro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumeroPaginasLivro, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtDataPublicacaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(86, Short.MAX_VALUE))))
        );
        pnCadastroLivroLayout.setVerticalGroup(
            pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLivroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarLivro))
                .addGap(18, 18, 18)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPublicacao)
                    .addComponent(txtDataPublicacaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroPaginas)
                    .addComponent(txtNumeroPaginasLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreco)
                    .addComponent(txtPrecoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(txtGeneroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCopiasVendidas)
                    .addComponent(txtCopiasVendidasLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastroLivroLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbLivroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdicionarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAdicionarAutor))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lblTitulo.getAccessibleContext().setAccessibleName("");

        btnLivroNovo.setText("Novo");
        btnLivroNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroNovoActionPerformed(evt);
            }
        });

        btnLivroSalvar.setText("Salvar");
        btnLivroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroSalvarActionPerformed(evt);
            }
        });

        btnLivroCancelar.setText("Cancelar");
        btnLivroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroCancelarActionPerformed(evt);
            }
        });

        btnLivroEditar.setText("Editar");
        btnLivroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroEditarActionPerformed(evt);
            }
        });

        btnLivroExcluir.setText("Excluir");
        btnLivroExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroExcluirActionPerformed(evt);
            }
        });

        btnLivroPesquisar.setText("Pesquisar");
        btnLivroPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroPesquisarActionPerformed(evt);
            }
        });

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Publicação", "Duração", "Preço", "Gênero", "Vendidas", "Diretor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLivros);

        btnSairCadastroLivro.setText("Sair");
        btnSairCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnLivroNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLivroSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLivroCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLivroEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLivroExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLivroPesquisar))
                    .addComponent(pnCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSairCadastroLivro)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(pnCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLivroSalvar)
                    .addComponent(btnLivroCancelar)
                    .addComponent(btnLivroEditar)
                    .addComponent(btnLivroExcluir)
                    .addComponent(btnLivroPesquisar)
                    .addComponent(btnLivroNovo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSairCadastroLivro)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLivroActionPerformed

    private void txtCopiasVendidasLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCopiasVendidasLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCopiasVendidasLivroActionPerformed

    private void btnSairCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroLivroActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairCadastroLivroActionPerformed
    //botão de novo cadastro
    private void btnLivroNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroNovoActionPerformed
            
        }
    }//GEN-LAST:event_btnLivroNovoActionPerformed
    //botão de cancelar
    private void btnLivroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroCancelarActionPerformed
                
    }//GEN-LAST:event_btnLivroCancelarActionPerformed
    //botão de salvar
    private void btnLivroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroSalvarActionPerformed
      
    }//GEN-LAST:event_btnLivroSalvarActionPerformed
    //botão adicionar Autor e iniciar cadastro
    private void btnAdicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAutorActionPerformed
        
    }//GEN-LAST:event_btnAdicionarAutorActionPerformed
    //botão adicionar editora e iniciar cadastro    //clicando na tabela para editar
    private void tblLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLivrosMouseClicked
       
        
    }//GEN-LAST:event_tblLivrosMouseClicked
    //Bortão editar cadastro
    private void btnLivroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroEditarActionPerformed
              
        
    }//GEN-LAST:event_btnLivroEditarActionPerformed
    //botão de exlcuir cadastro
    private void btnLivroExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroExcluirActionPerformed
      
       
    }//GEN-LAST:event_btnLivroExcluirActionPerformed
    //botão pesquisar que ativa o botão ok e inicia a pesquisa 
    private void btnLivroPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroPesquisarActionPerformed
       
        }
        
    }//GEN-LAST:event_btnLivroPesquisarActionPerformed
    //botão ok de pesquisar o Livro
    private void btnPesquisarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarLivroActionPerformed
       
    }//GEN-LAST:event_btnPesquisarLivroActionPerformed

    private void cmbLivroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLivroAutorActionPerformed
       
    }//GEN-LAST:event_cmbLivroAutorActionPerformed

    private void cmbLivroAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbLivroAutorMouseClicked
        
    }//GEN-LAST:event_cmbLivroAutorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAutor;
    private javax.swing.JButton btnLivroCancelar;
    private javax.swing.JButton btnLivroEditar;
    private javax.swing.JButton btnLivroExcluir;
    private javax.swing.JButton btnLivroNovo;
    private javax.swing.JButton btnLivroPesquisar;
    private javax.swing.JButton btnLivroSalvar;
    private javax.swing.JButton btnPesquisarLivro;
    private javax.swing.JButton btnSairCadastroLivro;
    private javax.swing.JComboBox<String> cmbLivroAutor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdicionarAutor;
    private javax.swing.JLabel lblCopiasVendidas;
    private javax.swing.JLabel lblDataPublicacao;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNumeroPaginas;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnCadastroLivro;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtCopiasVendidasLivro;
    private javax.swing.JFormattedTextField txtDataPublicacaoLivro;
    private javax.swing.JTextField txtGeneroLivro;
    private javax.swing.JTextField txtNumeroPaginasLivro;
    private javax.swing.JTextField txtPrecoLivro;
    private javax.swing.JTextField txtTituloLivro;
    // End of variables declaration//GEN-END:variables
}
